version: "3.7"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - 9000:9000
#    restart: unless-stopped
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
#    networks:
#      - sonarqube-net

# networks:
#  sonarqube-net:
